services:
  - type: web
    name: revista-montaje-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    build:
      packages:
        - poppler-utils
