services:
  - type: web
    name: revista-montaje-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=1 --threads=1 --timeout=120
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
    build:
      packages:
        - poppler-utils
